### ISSUE TITLE
Migrations are not running on deployment

### ISSUE THREAD

**Issue by LeonS** [ThoughtWorksStudios/eb_deployer#53]
Hi, 
The migrations are nut running on deployment (with rake eb:deploy), do I have to configure something to let them run?
I'm using the default config which got created by using "rails generate eb_deployer:install". When I login into the created EC2 instance and run the command by myself it works.
Thank you.

**Comment by xli** [comment]
Hi @LeonS,

Migration is on your own. Because eb deployer does not know how you want it to be run.
One option is getting it run on leader node (only one leader node exists, hence you can run on it)
Here is quick guide:
  create an ebextention config file contains:
----------------config file content----------
container_commands:
  mark_leader:
    command: "sudo -u tomcat touch /tmp/need_check_migration"
    leader_only: true
------------- end ------------
Then put the following code in an Rails initializer file:
-----------------start--------
if File.exists?('/tmp/need_check_migration')
  FileUtils.rm_rf('/tmp/need_check_migration')
  ActiveRecord::Migrator.migrate(Rails.root.join('db', 'migrate'))
end
----------------- end ---------------

**Comment by LeonS** [comment]
Hi @xli ,

wow that was a quick answer.
Thanks so much for that, will be in SF next year and you will get a beer , thats for sure.
The EB documentation is saying that migrations are run automatically, so that was the reason why I was confused. Thanks for the clarity :)

**Comment by xli** [comment]
Hi @LeonS 

You're right.
Elasticbeanstalk Rails environment will run migration for you.
eb_deployer does nothing for it. 
The code example I showed you are used for our JRuby rails app running on Tomcat environment.

I just checked out Rails environment deployment, it runs db migration. But it failed because of database connection issue, the following error is found in my rails app log:

    F, [2015-08-18T17:41:02.318445 #20743] FATAL -- : 
    PG::ConnectionBad (could not connect to server: Connection timed out
            Is the server running on host "xr1shur4j82y1hm.ccxjobfetnvs.us-west-1.rds.amazonaws.com"     (10.197.67.111) and accepting
            TCP/IP connections on port 5432?
    ):
      activerecord (4.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
      activerecord (4.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
      activerecord (4.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
      activerecord (4.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'

There is /var/log/eb-activity.log, it should contain something like the followings:

     [CMD-Startup/StartupStage0/AppDeployPreHook/12_db_migration.sh] : Completed activity. Result:

But I could not find any other logs related to migration. I think elastic beanstalk should fail the deployment if migration failed.

It maybe because the default configuration uses 'm1.small' ec2 instance type. Not sure why the database connection won't have any problem after the server is up running.

**Comment by xli** [comment]
After I updated to use 'm3.medium', the migration ran successfully.

**Comment by LeonS** [comment]
Hi @xli ,

thanks again for the deep dive into the problem.
So it depends on the power of the machine if the database connection gets established in time for the migrations?
That's weird, will contact AWS about that. 
I see 2 possible solutions: The deployment should fail or wait with a timeout for the establishment of the database connection.

Cheers 
Leon
